spring:
  datasource:
    url: jdbc:postgresql://db:5432/bill-app
    username: bills
    password: bills123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always
debug: true
trace: true